<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-I6T4BAQ" ignored="0" name="Test" tests="1" failures="1" timestamp="21 Jul 2020 06:20:11 GMT" time="14.411" errors="0">
  <testcase name="@AfterClass closeDriver" time="0.001" classname="runner.TestRunner">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at core.Context.closeDriver(Context.java:192)
at runner.TestRunner.closeDriver(TestRunner.java:27)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- @AfterClass closeDriver -->
  <testcase name="runScenario" time="14.088" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="expected [4] but found [Display is 1]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [Display is 1]
at core.WinniumSteps.verifyResult(WinniumSteps.java:71)
at âœ½.I validate the result as "4" in calculator(src/test/resources/feature/desktop/Calculator.feature:11)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Test -->
